version: '2.1'

services:
    
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
     working_dir: /var/www/html
     volumes:
       - ./wp:/var/www/html

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin
     environment:
       - PMA_ARBITRARY=1
     restart: always
     links:
       - "db:db"
     ports:
       - 8080:80
     volumes:
       - /sessions

   wpcli:
     image: tatemz/wp-cli
     volumes_from:
       - wordpress
     links:
       - db:mysql
     entrypoint: wp
     command: "--info"
         
volumes:
    db_data:


# https://docs.docker.com/compose/wordpress/
# https://medium.com/@tatemz/using-wp-cli-with-docker-21b0ab9fab79#.8wstldacz
# alias wp="docker-compose run --rm wpcli"
